server:
  port: 8090
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: http://localhost:8092
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: coceso
          uri: http://localhost:8093
          predicates:
            - Path=/coceso/**
          filters:
            - StripPrefix=1

logging:
  level:
    root: info
