name: Build mls-db Docker image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/docker-db.yml
      - db/**

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/docker-build.yml@main
    with:
      DOCKER_CONTEXT: ./db
      DOCKER_NAME: wrkfmdit/mls-db
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
